### ISSUE TITLE
Unable to install Pycausality

### ISSUE THREAD

**Issue by newbietogitdotcom** [ZacKeskin/PyCausality#8]
Hi I tried to run pip install PyCausality

It gives me below error even when I already have numpy installed. I tried upgrading pip, installing numpy again etc but no success yet, can you please help me ?

Collecting PyCausality
  Using cached PyCausality-1.2.0-py3-none-any.whl.metadata (714 bytes)
Requirement already satisfied: pandas in /Users/h0c07af/anaconda3/lib/python3.10/site-packages (from PyCausality) (1.5.3)
Requirement already satisfied: statsmodels in /Users/h0c07af/anaconda3/lib/python3.10/site-packages (from PyCausality) (0.13.5)
Requirement already satisfied: numpy in /Users/h0c07af/anaconda3/lib/python3.10/site-packages (from PyCausality) (1.23.5)
Collecting python-dateutil==2.6.1 (from PyCausality)
  Using cached python_dateutil-2.6.1-py2.py3-none-any.whl.metadata (1.1 kB)
Collecting nose (from PyCausality)
  Using cached nose-1.3.7-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: six>=1.5 in /Users/h0c07af/anaconda3/lib/python3.10/site-packages (from python-dateutil==2.6.1->PyCausality) (1.16.0)
INFO: pip is looking at multiple versions of pandas to determine which version is compatible with other requirements. This could take a while.
Collecting pandas (from PyCausality)
  Using cached pandas-2.2.3-cp310-cp310-macosx_11_0_arm64.whl.metadata (89 kB)
  Using cached pandas-2.2.2-cp310-cp310-macosx_11_0_arm64.whl.metadata (19 kB)
  Using cached pandas-2.2.1-cp310-cp310-macosx_11_0_arm64.whl.metadata (19 kB)
  Using cached pandas-2.2.0-cp310-cp310-macosx_11_0_arm64.whl.metadata (19 kB)
  Using cached pandas-2.1.4-cp310-cp310-macosx_11_0_arm64.whl.metadata (18 kB)
  Using cached pandas-2.1.3-cp310-cp310-macosx_11_0_arm64.whl.metadata (18 kB)
  Using cached pandas-2.1.2-cp310-cp310-macosx_11_0_arm64.whl.metadata (18 kB)
INFO: pip is still looking at multiple versions of pandas to determine which version is compatible with other requirements. This could take a while.
  Using cached pandas-2.1.1-cp310-cp310-macosx_11_0_arm64.whl.metadata (18 kB)
  Using cached pandas-2.1.0-cp310-cp310-macosx_11_0_arm64.whl.metadata (18 kB)
  Using cached pandas-2.0.3-cp310-cp310-macosx_11_0_arm64.whl.metadata (18 kB)
  Using cached pandas-2.0.2-cp310-cp310-macosx_11_0_arm64.whl.metadata (18 kB)
  Using cached pandas-2.0.1-cp310-cp310-macosx_11_0_arm64.whl.metadata (18 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Using cached pandas-2.0.0-cp310-cp310-macosx_11_0_arm64.whl.metadata (18 kB)
  Using cached pandas-1.5.2-cp310-cp310-macosx_11_0_arm64.whl.metadata (11 kB)
  Using cached pandas-1.5.1-cp310-cp310-macosx_11_0_arm64.whl.metadata (11 kB)
  Using cached pandas-1.5.0-cp310-cp310-macosx_11_0_arm64.whl.metadata (11 kB)
  Using cached pandas-1.4.4-cp310-cp310-macosx_11_0_arm64.whl.metadata (12 kB)
  Using cached pandas-1.4.3-cp310-cp310-macosx_11_0_arm64.whl.metadata (12 kB)
  Using cached pandas-1.4.2-cp310-cp310-macosx_11_0_arm64.whl.metadata (12 kB)
  Using cached pandas-1.4.1-cp310-cp310-macosx_11_0_arm64.whl.metadata (12 kB)
  Using cached pandas-1.4.0-cp310-cp310-macosx_11_0_arm64.whl.metadata (12 kB)
  Using cached pandas-1.3.5-cp310-cp310-macosx_11_0_arm64.whl.metadata (12 kB)
  Using cached pandas-1.3.4-cp310-cp310-macosx_11_0_arm64.whl.metadata (12 kB)
  Using cached pandas-1.3.3.tar.gz (4.7 MB)
  Installing build dependencies ... [?25ldone
[?25h  Getting requirements to build wheel ... [?25lerror
  [1;31merror[0m: [1msubprocess-exited-with-error[0m
  
  [31m×[0m [32mGetting requirements to build wheel[0m did not run successfully.
  [31m│[0m exit code: [1;36m1[0m
  [31m╰─>[0m [31m[17 lines of output][0m
  [31m   [0m Traceback (most recent call last):
  [31m   [0m   File "/Users/h0c07af/anaconda3/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
  [31m   [0m     main()
  [31m   [0m   File "/Users/h0c07af/anaconda3/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
  [31m   [0m     json_out['return_val'] = hook(**hook_input['kwargs'])
  [31m   [0m   File "/Users/h0c07af/anaconda3/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
  [31m   [0m     return hook(config_settings)
  [31m   [0m   File "/private/var/folders/7_/v2swbqgd2nn_yj0tgfqs5z6r0000gq/T/pip-build-env-avdlkw5g/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
  [31m   [0m     return self._get_build_requires(config_settings, requirements=[])
  [31m   [0m   File "/private/var/folders/7_/v2swbqgd2nn_yj0tgfqs5z6r0000gq/T/pip-build-env-avdlkw5g/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
  [31m   [0m     self.run_setup()
  [31m   [0m   File "/private/var/folders/7_/v2swbqgd2nn_yj0tgfqs5z6r0000gq/T/pip-build-env-avdlkw5g/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 503, in run_setup
  [31m   [0m     super().run_setup(setup_script=setup_script)
  [31m   [0m   File "/private/var/folders/7_/v2swbqgd2nn_yj0tgfqs5z6r0000gq/T/pip-build-env-avdlkw5g/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 318, in run_setup
  [31m   [0m     exec(code, locals())
  [31m   [0m   File "<string>", line 18, in <module>
  [31m   [0m ModuleNotFoundError: No module named 'numpy'
  [31m   [0m [31m[end of output][0m
  
  [1;35mnote[0m: This error originates from a subprocess, and is likely not a problem with pip.
[?25h[1;31merror[0m: [1msubprocess-exited-with-error[0m

[31m×[0m [32mGetting requirements to build wheel[0m did not run successfully.
[31m│[0m exit code: [1;36m1[0m
[31m╰─>[0m See above for output.

[1;35mnote[0m: This error originates from a subprocess, and is likely not a problem with pip.
Note: you may need to restart the kernel to use updated packages.

**Comment by ZacKeskin** [comment]
Looks like a dependency issue. Were you able to resolve this yet? 

The package is likely to be incompatible with newer versions of packages including, pandas, simply because it is not maintained actively enough to require ongoing compatibility releases.

I would suggest starting with a new, clean conda environment and trying to install the package in there.
